# Generated by Django 5.1.4 on 2026-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('internal', 'Internal — booker leases this building'), ('external', 'External — booker does not lease this building')], default='external', help_text='Set automatically: internal if the company leases the building, else external.', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_required',
            field=models.BooleanField(default=True, help_text='False for internal bookings (included in lease); True for external (paid).'),
        ),
    ]
