# Generated by Django 5.1.4 on 2026-06-12 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_checked_in_at'),
        ('facilities', '0003_facility_owner_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars')),
                ('comment', models.TextField(blank=True)),
                ('reviewer_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facilities.facility')),
            ],
            options={
                'db_table': 'bookings_bookingreview',
                'ordering': ['-created_at'],
            },
        ),
    ]
