# Generated by Django 5.1.4 on 2026-06-08 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('conference_room', 'Conference Room'), ('meeting_room', 'Meeting Room'), ('event_hall', 'Event Hall'), ('podcast_studio', 'Podcast Studio'), ('printing_room', 'Printing Room'), ('3d_printer', '3D Printer'), ('cafeteria', 'Cafeteria'), ('other', 'Other')], max_length=30)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities, e.g. ["WiFi", "Projector", "AC", "Whiteboard"]')),
                ('booking_rules', models.JSONField(blank=True, default=dict, help_text='e.g. {"min_hours": 1, "max_hours": 8, "advance_days": 1, "cancellation_hours": 24}')),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='workspace.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='workspace.floor')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facilities_facility',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='facility_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.facility')),
            ],
            options={
                'db_table': 'facilities_facilityimage',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
