# Generated by Django 5.1.4 on 2026-06-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, external visitors can book this facility without logging in.'),
        ),
    ]
