# Generated by Django 5.1.4 on 2026-06-11 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('facilities', '0002_facility_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_facilities', to='companies.company'),
        ),
    ]
