# Generated by Django 5.1.4 on 2026-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_owner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link to a hosted cover image. Free hosts: imgbb.com, postimages.org.', max_length=500),
        ),
    ]
