# Generated by Django 5.1.4 on 2026-06-08 11:46

import apps.visitors.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(max_length=300)),
                ('pass_code', models.CharField(default=apps.visitors.models._generate_pass_code, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('valid_from', models.TimeField()),
                ('valid_until', models.TimeField()),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_passes', to='workspace.building')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitor_passes', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
