# Generated by Django 5.1.4 on 2026-06-09 11:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('utilities', 'Utilities (Electricity / Water)'), ('catering', 'Catering / Pantry'), ('cleaning', 'Cleaning / Housekeeping'), ('maintenance', 'Maintenance / Repairs'), ('supplies', 'Supplies'), ('security', 'Security'), ('internet', 'Internet / Telecom'), ('other', 'Other')], default='other', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, help_text='Optional — leave blank for an operator-wide vendor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='workspace.building')),
            ],
            options={
                'db_table': 'vendors_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vendor_bills/')),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='workspace.building')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendors_vendorbill',
                'ordering': ['-bill_date', 'bill_number'],
            },
        ),
    ]
