# Generated by Django 5.1.4 on 2026-06-10 17:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessee_name', models.CharField(max_length=150)),
                ('lessee_email', models.EmailField(blank=True, max_length=254)),
                ('lessee_phone', models.CharField(blank=True, max_length=15)),
                ('lessee_company', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_leases', to='workspace.desk')),
                ('lessor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_leases', to='companies.company')),
            ],
            options={
                'db_table': 'subleasing_seatlease',
                'ordering': ['-start_date'],
            },
        ),
    ]
