# Generated by Django 5.1.4 on 2026-06-11 12:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('subleasing', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True, help_text='Accepting applications')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_listings', to='workspace.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_listings', to='workspace.floor')),
                ('lessor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_listings', to='companies.company')),
            ],
            options={
                'db_table': 'subleasing_seatlisting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('seats_requested', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='subleasing.seatlisting')),
            ],
            options={
                'db_table': 'subleasing_seatapplication',
                'ordering': ['-created_at'],
            },
        ),
    ]
