# Generated by Django 5.1.4 on 2026-06-08 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('booking_created', 'Booking Created'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('payment_recorded', 'Payment Recorded'), ('document_uploaded', 'Document Uploaded'), ('maintenance_created', 'Maintenance Ticket Created'), ('maintenance_assigned', 'Maintenance Ticket Assigned'), ('maintenance_resolved', 'Maintenance Ticket Resolved'), ('company_created', 'Company Created'), ('company_status_changed', 'Company Status Changed'), ('visitor_checked_in', 'Visitor Checked In'), ('visitor_checked_out', 'Visitor Checked Out'), ('application_submitted', 'Incubation Application Submitted'), ('application_accepted', 'Incubation Application Accepted'), ('application_rejected', 'Incubation Application Rejected'), ('system', 'System Action')], db_index=True, max_length=40)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
