# Generated by Django 5.1.4 on 2026-06-08 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workspace_building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_number', models.IntegerField(help_text='0 = Ground Floor, 1 = 1st Floor, etc.')),
                ('name', models.CharField(help_text='e.g. Ground Floor, 1st Floor', max_length=100)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='workspace.building')),
            ],
            options={
                'db_table': 'workspace_floor',
                'ordering': ['building', 'floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(help_text='e.g. 101, A-205', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Optional display name', max_length=100)),
                ('room_type', models.CharField(choices=[('cabin', 'Private Cabin'), ('open_space', 'Open Space'), ('meeting_room', 'Meeting Room'), ('event_hall', 'Event Hall'), ('storage', 'Storage'), ('other', 'Other')], default='open_space', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='workspace.floor')),
            ],
            options={
                'db_table': 'workspace_room',
                'ordering': ['floor', 'room_number'],
                'unique_together': {('floor', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_number', models.CharField(help_text='e.g. P-01, B-15, EV-03', max_length=20)),
                ('slot_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Scooter'), ('ev', 'EV Charging')], default='car', max_length=10)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='workspace.building')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parking', to='companies.company')),
            ],
            options={
                'db_table': 'workspace_parkingslot',
                'ordering': ['building', 'slot_number'],
                'unique_together': {('building', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desk_code', models.CharField(help_text='e.g. D-101-A, HOT-01', max_length=20)),
                ('desk_type', models.CharField(choices=[('dedicated', 'Dedicated Desk'), ('hot_desk', 'Hot Desk')], default='hot_desk', max_length=20)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='False if desk is under maintenance or permanently occupied')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, help_text='Set for dedicated desks — which company this desk belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_desks', to='companies.company')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='workspace.room')),
            ],
            options={
                'db_table': 'workspace_desk',
                'ordering': ['room', 'desk_code'],
                'unique_together': {('room', 'desk_code')},
            },
        ),
    ]
