# Generated by Django 5.1.4 on 2026-06-08 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='esign/requests/%Y/%m/')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('partially_signed', 'Partially Signed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='esign/certificates/%Y/%m/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_name', models.CharField(max_length=150)),
                ('signing_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 signature image or typed name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_records', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='esign.signaturerequest')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('request', 'signer_email')},
            },
        ),
    ]
