import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER


def generate_certificate(signature_request):
    """Generate a PDF certificate of completion for a fully-signed request."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=2 * cm, leftMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('cert_title', parent=styles['Title'], alignment=TA_CENTER, fontSize=18)
    heading_style = ParagraphStyle('cert_heading', parent=styles['Heading2'], fontSize=12)
    body_style = styles['Normal']
    small_style = ParagraphStyle('cert_small', parent=styles['Normal'], fontSize=9, textColor=colors.grey)

    story = []

    story.append(Paragraph('Certificate of Digital Signature', title_style))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph('This document certifies the following signatures were collected.', body_style))
    story.append(Spacer(1, 0.6 * cm))

    # Document info table
    info_data = [
        ['Document', signature_request.title],
        ['Created by', signature_request.created_by.get_full_name() or signature_request.created_by.email],
        ['Company', str(signature_request.company)],
        ['Status', signature_request.status.replace('_', ' ').title()],
    ]
    info_table = Table(info_data, colWidths=[4 * cm, 12 * cm])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f4ff')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dde3f0')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f8faff')]),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.8 * cm))

    story.append(Paragraph('Signature Records', heading_style))
    story.append(Spacer(1, 0.3 * cm))

    for rec in signature_request.records.filter(status='signed').order_by('signed_at'):
        rec_data = [
            ['Signer', f"{rec.signer_name} <{rec.signer_email}>"],
            ['Signed at', rec.signed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if rec.signed_at else '—'],
            ['IP Address', rec.ip_address or '—'],
            ['Signature', rec.signature_data[:120] + '...' if len(rec.signature_data) > 120 else rec.signature_data],
        ]
        rec_table = Table(rec_data, colWidths=[4 * cm, 12 * cm])
        rec_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f5f5f5')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(rec_table)
        story.append(Spacer(1, 0.4 * cm))

    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph(
        f'Certificate generated by CoWorkHub. Document ID: {signature_request.id}',
        small_style
    ))

    doc.build(story)
    return buffer.getvalue()
