# Generated by Django 5.1.4 on 2026-06-08 10:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.CharField(help_text='E.g. 2026-Q1', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('problem_statement', models.TextField()),
                ('solution', models.TextField()),
                ('market_size', models.TextField(blank=True)),
                ('traction', models.TextField(blank=True)),
                ('funding_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_type', models.CharField(blank=True, choices=[('grant', 'Grant'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('bridge', 'Bridge Round'), ('other', 'Other')], max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are visible to Super Admins only')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubation_notes', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incubation.incubationapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(choices=[('fintech', 'Fintech'), ('edtech', 'Edtech'), ('healthtech', 'Healthtech'), ('agritech', 'Agritech'), ('saas', 'SaaS'), ('ecommerce', 'E-Commerce'), ('logistics', 'Logistics & Supply Chain'), ('cleantech', 'Cleantech'), ('ai_ml', 'AI / ML'), ('iot', 'IoT'), ('other', 'Other')], default='other', max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP'), ('early_traction', 'Early Traction'), ('growth', 'Growth'), ('scale', 'Scale')], default='idea', max_length=20)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='incubation/logos/')),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='incubation/pitch_decks/')),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='incubation/business_plans/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incubationapplication',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='incubation.startupprofile'),
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_type', models.CharField(choices=[('grant', 'Grant'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('bridge', 'Bridge Round'), ('other', 'Other')], max_length=20)),
                ('amount_sought', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('seeking', 'Seeking'), ('closed', 'Closed')], default='planning', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('investors', models.TextField(blank=True, help_text='Comma-separated investor names')),
                ('notes', models.TextField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='incubation.startupprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='incubationapplication',
            unique_together={('startup', 'cohort')},
        ),
    ]
